name: Deploy Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'temp-docs/**'
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: temp-docs
        
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: temp-docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Remove old docs if they exist
          rm -rf ../docs
          
          # Move the built files to docs folder
          mv build ../docs
          
          # Add and commit the changes
          git add ../docs
          git commit -m "docs: update documentation"
          
          # Push the changes
          git push origin main
