name: Deploy Documentation

on:
  push:
    branches: ["main"]
    paths:
      - "docusaurus/**"
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "docusaurus/**"
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docusaurus

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docusaurus/package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm ci

      - name: Build website
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true
