# GitHub Actions workflow for SonarQube test coverage reporting
# Requires SONAR_TOKEN secret and SonarQube server URL (SONAR_HOST_URL) set in repository secrets

name: SonarQube Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload coverage to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
